name: Check Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1" # every Monday at 9am UTC

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 100..=399
            --exclude '^https://www\.linkedin\.com'
            --exclude '^https://www\.lyft\.com'
            --exclude '^https://www\.spotify\.com'
            --exclude '^https://www\.intel\.com'
            --exclude '^https://slack\.flyte\.org'
            readme.md
          fail: true
